/// Division modulo 0xfffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364141, the Secp256k1 scalar field order
/// To replace with more efficient method using non-determinism later.

%macro mulmodn_secp_scalar
    // stack: x, y
    %secp_scalar
    // stack: N, x, y
    SWAP2
    // stack: y, x, N
    MULMOD
%endmacro

%macro squaremodn_secp_scalar
    // stack: x
    DUP1
    // stack: x, x
    %mulmodn_secp_scalar
%endmacro

// Computes the inverse modulo N using x^-1 = x^(N-2) mod N and square-and-multiply modular exponentiation.
%macro inverse_secp_scalar
    DUP1
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    %squaremodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    %squaremodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    %squaremodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    %squaremodn_secp_scalar
    %squaremodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    %squaremodn_secp_scalar
    %squaremodn_secp_scalar
    %squaremodn_secp_scalar
    %squaremodn_secp_scalar
    %squaremodn_secp_scalar
    %squaremodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    %squaremodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    %squaremodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    %squaremodn_secp_scalar
    %squaremodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    %squaremodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    %squaremodn_secp_scalar
    %squaremodn_secp_scalar
    %squaremodn_secp_scalar
    %squaremodn_secp_scalar
    %squaremodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    %squaremodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    %squaremodn_secp_scalar
    %squaremodn_secp_scalar
    %squaremodn_secp_scalar
    %squaremodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    %squaremodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    %squaremodn_secp_scalar
    DUP2
    %mulmodn_secp_scalar
    SWAP1
    // stack: x, x^-1
    POP
    // stack: x^-1
%endmacro
