%macro secp_lift_x
    // stack: x, v
    DUP1
    // stack: x, x, v
    %cubemodn_secp
    // stack: x^3, x, v
    PUSH 7
    // stack: 7, x^3, x, v
    %addmodn_secp
    // stack: x^3+7, x, v
    DUP1
    // stack: x^3+7, x^3+7, x, v
    %sqrt_secp
    // stack: y, x^3+7, x, v
    SWAP1
    // stack: x^3+7, y, x, v
    DUP2
    // stack: y, x^3+7, y, x, v
    %squaremodn_secp
    // stack: y^2, x^3+7, y, x, v
    EQ
    // stack: sqrtOk, y, x, v
    SWAP3
    // stack: v, y, x, sqrtOk
    DUP2
    // stack: y, v, y, x, sqrtOk
    PUSH 1
    // stack: 1, y, v, y, x, sqrtOk
    AND
    // stack: 1 & y, v, y, x, sqrtOk
    PUSH 27
    // stack: 27, 1 & y, v, y, x, sqrtOk
    SWAP1
    // stack: 1 & y, 27, v, y, x, sqrtOk
    SWAP2
    // stack: v, 27, 1 & y, y, x, sqrtOk
    SUB
    // stack: v - 27, 1 & y, y, x, sqrtOk
    EQ
    // stack: correctParity, y, x, sqrtOk
    DUP2
    // stack: y, correctParity, y, x, sqrtOk
    %secp_base
    // stack: N, y, correctParity, y, x, sqrtOk
    SUB
    // stack: N - y, correctParity, y, x, sqrtOk
    SWAP1
    // stack: correctParity, N - y, y, x, sqrtOk
    %select_bool
    // stack: goody, x, sqrtOk
    SWAP2
    // stack: sqrtOk, x, goody
%endmacro

%macro cubemodn_secp
    // stack: x
    DUP1
    // stack: x, x
    %squaremodn_secp
    // stack: x^2, x
    %mulmodn_secp
%endmacro

%macro addmodn_secp
    // stack: x, y
    %secp_base
    // stack: N, x, y
    SWAP2
    // stack: y, x, N
    ADDMOD
%endmacro

// Returns sqrt(x). Computed as x^(q+1)/4, with q the Secp base field order.
/// To replace with more efficient method using non-determinism later.
%macro sqrt_secp
    // stack: x
    DUP1
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    %squaremodn_secp
    %squaremodn_secp
    %squaremodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    DUP2
    %mulmodn_secp
    %squaremodn_secp
    %squaremodn_secp
    SWAP1
    // stack: x, x^-1
    POP
    // stack: x^-1
%endmacro