[package]
name = "plonky2_field"
description = "Finite field arithmetic"
version = "0.1.0"
edition = "2021"

[dependencies]
plonky2_util = { path = "../util" }
anyhow = "1.0.40"
itertools = "0.10.0"
num = { version = "0.4", features = [ "rand" ] }
rand = { version = "0.8.4", optional = true }
serde = { version = "1.0", features = ["derive"] }
unroll = "0.1.5"
static_assertions = "1.1.0"

[dev-dependencies]
rand = "0.8.4"
